ダブルキラー完成
ykundesu/SuperNewRoles pull request #194
Opened 2022-06-24 08:28 UTC by jukimaguro1

キルボタン二つ持ってるいんぽです。
それだけの役職です。
それぞれでキルク設定できます

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/Buttons/Buttons.cs
> +        public static CustomButton DoubleKillerSubKillButton;
細かいですけど、subとmainの上下は逆がいいと思います

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/Buttons/Buttons.cs
> +                8
8じゃなくて49だと思います

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/CustomOption/CustomOptionDate.cs
> +            DoubleKillerSubCoolTime = CustomOption.Create(568, false, CustomOptionType.Impostor, "SubCoolSetting", 30f, 2.5f, 60f, 2.5f, DoubleKillerOption, format: "unitSeconds");
subのformatはsecondなのにmainには無いのは大丈夫ですか？

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/Patch/FixedUpdate.cs
>                              Minimalist.FixedUpdate.Postfix();
Fixed Updateはミニマリストに統合した方がいいと思います

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/Roles/DoubleKiller.cs
> +                    HudManager.Instance.KillButton.buttonLabelText.SetText("");
純正キルボ消す処理ですが、Set Active(false)のみで良かったはずです。
(ミニマリスト参照)

2022-06-24 08:34 UTC, satsumaimoamo commented on SuperNewRoles/Roles/DoubleKiller.cs
> +                if (RoleClass.DoubleKiller.NoKill == true)
NoKillは常にtrueなのでここのifとRoleClassのNokillは不要だと思います

2022-06-24 08:34 UTC, jukimaguro1 commented on SuperNewRoles/CustomOption/CustomOptionDate.cs
> +            DoubleKillerSubCoolTime = CustomOption.Create(568, false, CustomOptionType.Impostor, "SubCoolSetting", 30f, 2.5f, 60f, 2.5f, DoubleKillerOption, format: "unitSeconds");
純正キルボタン使ってた時のと同じままやんけごみぃ

2022-06-24 08:35 UTC, jukimaguro1 commented on SuperNewRoles/Roles/DoubleKiller.cs
> +                    HudManager.Instance.KillButton.buttonLabelText.SetText("");
ダブラル(((ry

2022-06-24 08:35 UTC, yurinakira commented on CreditsData.json
> +{"name":"windows7","id":100}
windows7さんはダブルキラーに関係していますか？
関係していないのであれば、ステージングミスだと思いますので、このファイルはコミットすべきではないと思ってます。

2022-06-24 08:35 UTC, satsumaimoamo commented on SuperNewRoles/Roles/DoubleKiller.cs
> +                    HudManager.Instance.KillButton.buttonLabelText.SetText("");
リファクタリングされました

2022-06-24 08:36 UTC, jukimaguro1 commented on CreditsData.json
> +{"name":"windows7","id":100}
ここいじってないのですがこれは、、、、()

2022-06-24 08:37 UTC, yurinakira commented on SNRDevTools/transmoto.txt
> +DoubleKillerTitle1
最後の1って必要ですか？

2022-06-24 08:37 UTC, satsumaimoamo commented on CreditsData.json
> +{"name":"windows7","id":100}
たぶんdevelop通さずにmainに直コミットしたやつがいるのでそのせいですね

2022-06-24 08:37 UTC, jukimaguro1 commented on SNRDevTools/transmoto.txt
> +DoubleKillerTitle1
全役職ついてるはずですが、、、、

2022-06-24 08:38 UTC, satsumaimoamo commented on SNRDevTools/transmoto.txt
> +DoubleKillerTitle1
必要ですね

2022-06-24 08:40 UTC, Kurato-Tsukishiro requested changes

2022-06-24 08:40 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Buttons/Buttons.cs
> +                49
こっちが8ですね

2022-06-24 08:45 UTC, yurinakira commented on SuperNewRoles/Roles/DoubleKiller.cs
> +            public static PlayerControl DoubleKillersetTarget(bool onlyCrewmates = false, bool targetPlayersInVents = false, List<PlayerControl> untargetablePlayers = null, PlayerControl targetingPla
setが小文字
DoubleKillerSetTarget

2022-06-24 08:53 UTC, jukimaguro1 commented on SuperNewRoles/Roles/DoubleKiller.cs
> +            public static PlayerControl DoubleKillersetTarget(bool onlyCrewmates = false, bool targetPlayersInVents = false, List<PlayerControl> untargetablePlayers = null, PlayerControl targetingPla
Jackalからの移植なのでミスはないはずですが、、、、

2022-06-24 10:59 UTC, satsumaimoamo commented on SuperNewRoles/Roles/Minimalist.cs
> +                    DoubleKiller.SetDoubleKillerButton();
ダブルキラーの消去をここのPostFixにいれるよりも、
SetMinimalistButtonに入れた方がいいかもしれますん

2022-06-24 11:02 UTC, jukimaguro1 commented on SuperNewRoles/Roles/Minimalist.cs
> +                    DoubleKiller.SetDoubleKillerButton();
どういうことやねーん

2022-06-24 11:26 UTC, satsumaimoamo commented on SuperNewRoles/Roles/Minimalist.cs
> +                    DoubleKiller.SetDoubleKillerButton();
今はDoubleKiller.csのSetDoubleKillerButtonでキルボタンを消していますが、
minimalist.csのSetMinimalistButtonに入れたほうがいいということです

2022-06-24 11:48 UTC, jukimaguro1 commented on SuperNewRoles/Roles/Minimalist.cs
> +                    DoubleKiller.SetDoubleKillerButton();
あーそゆことね！(サボっただけ)

2022-06-25 00:30 UTC, yurinakira commented on SuperNewRoles/Roles/Minimalist.cs
> +                //ダブルキラーの純正キルボタン消去
細かいんですけど、別行にコメント書く場合は、該当コードの上の行に追加するのがオーソドックスですね。

2022-06-25 02:02 UTC, jukimaguro1 commented on SuperNewRoles/Roles/Minimalist.cs
> +                //ダブルキラーの純正キルボタン消去
すまん他の役職に合わせただけなんだあ()

2022-06-25 05:16 UTC, ykundesu commented
コンフク

2022-06-25 05:29 UTC, closed without merging