オールオープナー
ykundesu/SuperNewRoles pull request #304
Opened 2022-07-14 11:54 UTC by satsumaimoamo

スケルド・ミラではサボを修理
他では扉をすべて開けます

いずれも一度だけです
SHRではシェイプです

2022-07-15 17:39 UTC, Kurato-Tsukishiro requested changes
これらに加えて、
・ベントに入れる
・サボタージュができる
・キルができる

・SHR時タスクがクリアされない
・死後守護天使にならない(これは必要か分からない)

という問題があると思われます。

2022-07-15 17:39 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Intro/IntroDate.cs
> +        public static IntroDate AllOpenerIntro = new IntroDate("AllOpener", RoleClass.AllOpener.color, 1, RoleId.AllOpener);
TeamRoleType.Crewmateが抜けています

2022-07-15 17:39 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
> +                case RoleId.AllOpener:
クルーメイトなのにインポスターの視界設定が適応されています

2022-07-15 17:39 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Roles/RoleHelper.cs
> +                else if (RoleClass.AllOpener.AllOpenerPlayer.IsCheckListPlayerControl(player))
リファクタ後のコードになっていないです
(多分CRAの記載ですかね。CRAの方は修正しました)

2022-07-15 17:39 UTC, Kurato-Tsukishiro commented on SuperNewRoles/CustomOption/CustomOptionDate.cs
> +            AllOpenerOption = new CustomRoleOption(674, true, CustomOptionType.Crewmate, "AllOpenerName", RoleClass.AllOpener.color, 1);
674と675はイビル猫又と黒猫のIDと重複しています

2022-07-16 02:46 UTC, satsumaimoamo commented
全部修正しました

2022-07-16 05:21 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Patch/PlayerControlPatch.cs
> +                        case RoleId.AllCleaner:
違う役職になっていると思われます

2022-07-16 05:24 UTC, Kurato-Tsukishiro approved these changes

2022-07-25 07:31 UTC, satsumaimoamo commented on SuperNewRoles/Patch/PlayerControlPatch.cs
> +                        case RoleId.AllCleaner:
修正しました

2022-07-25 07:33 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Patch/PlayerControlPatch.cs
> +                        case RoleId.AllCleaner:
確認しました

2022-07-25 07:44 UTC, Kurato-Tsukishiro commented on SuperNewRoles/CustomOption/CustomOptionDate.cs
> +            AllOpenerPlayerCount = CustomOption.Create(683, true, CustomOptionType.Crewmate, "SettingPlayerCountName", CrewPlayers[0], CrewPlayers[1], CrewPlayers[2], CrewPlayers[3], AllOpenerOption)
ID重複しています「NeetIsAddWin」

2022-07-25 07:45 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Intro/IntroDate.cs
> +        public static IntroDate AllOpenerIntro = new IntroDate("AllOpener", RoleClass.AllOpener.color, 1, RoleId.AllOpener, TeamRoleType.Crewmate);
古いコードのままかと思われます

2022-07-25 07:46 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
> +                    RoleId.truelover, RoleId.FalseCharges, RoleId.MadMaker, RoleId.ToiletFan,RoleId.AllCleaner, RoleId.NiceButtoner)
RoleId.AllCleaner

2022-07-25 07:47 UTC, Kurato-Tsukishiro commented on SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
> +break;
何処にいるねん　このbreak;()

2022-07-25 08:01 UTC, satsumaimoamo commented on SuperNewRoles/Mode/SuperHostRoles/MorePatch.cs
> +                    RoleId.truelover, RoleId.FalseCharges, RoleId.MadMaker, RoleId.ToiletFan,RoleId.AllCleaner, RoleId.NiceButtoner)
修正しました

2022-07-25 08:01 UTC, satsumaimoamo commented on SuperNewRoles/Mode/SuperHostRoles/SyncSetting.cs
> +break;
RoleHelperで視界設定をするように変更しました

2022-08-16 07:01 UTC, closed without merging